image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - production
    - e2e

production:
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
    only:
        - master
e2e:
  image: cypress/browsers:node10.16.0-chrome77
  stage: e2e
  script:
    - cd e2e
    - yarn install --frozen-lockfile
    - yarn run cypress:run:record $CYPRESS_RECORD_KEY